Move update_key config from column_options to upper layer
trocco-io/embulk-output-kintone pull request #20
Opened 2022-03-11 06:41 UTC by yosuke-oka

update_keyは1つしか指定できないのでconfig.ymlでの層を一つ上にする。
破壊的変更ですが、以下のメリットが有るかと思います。
  - update, upsert時にcolumn_optionを省略することができるようになる
  - コード、config.ymlの記述がシンプルになる。

2022-03-15 08:32 UTC, kekekenta commented on src/main/java/org/embulk/output/kintone/KintoneOutputPlugin.java
> +                    throw new IllegalArgumentException("when mode is update and upsert, require update_key.");
```suggestion
                    throw new IllegalArgumentException("when mode is update or upsert, require update_key.");
```

2022-03-15 09:55 UTC, kekekenta commented on src/main/java/org/embulk/output/kintone/KintonePageOutput.java
> +            fieldCode + " in (" + String.join(",", queryValues) + ")"
`queryValues` って最大10,000件渡ってくると思うのですが、クエリ的には問題なくレスポンス返ってきそうでしょうか？

2022-03-15 09:57 UTC, kekekenta commented on src/main/java/org/embulk/output/kintone/KintonePageOutput.java
> +            fieldCode + " in (" + String.join(",", queryValues) + ")"
もともとなので、問題なさそうでした。

2022-03-16 06:44 UTC, kekekenta commented on src/main/java/org/embulk/output/kintone/KintonePageOutput.java
> +        List<Record> distRecords = getRecordsByUpdateKey(updateKeys);
kintone側にすでに存在する（=upsert対象の）レコードということなので、
```suggestion
        List<Record> existingRecords = getExiststingRecordsByUpdateKey(updateKeys);
```

がわかりやすいかなと思いました！

2022-03-16 06:48 UTC, kekekenta approved these changes
LGTM

2022-03-16 09:14 UTC, d-hrs requested changes
ﾁｮｯﾄﾀﾞｹ。後でまた見ます

2022-03-16 09:14 UTC, d-hrs commented on src/main/java/org/embulk/output/kintone/KintoneOutputPlugin.java
> +                    throw new IllegalArgumentException("when mode is insert, require no update_key.");
```suggestion
                    throw new org.embulk.config.ConfigException("when mode is insert, require no update_key.");
```

2022-03-16 09:14 UTC, d-hrs commented on src/main/java/org/embulk/output/kintone/KintonePageOutput.java
> +import com.kintone.client.model.record.*;
ワイルドカードインポート使わないようお願いします！

2022-03-16 09:14 UTC, d-hrs commented on src/main/java/org/embulk/output/kintone/KintonePageOutput.java
> +                    if (records.size() == 10000) {
BATCH_SIZE的な定数にしてください！

2022-03-16 10:11 UTC, giwa approved these changes
LGTM

2022-03-16 10:57 UTC, d-hrs commented on src/main/java/org/embulk/output/kintone/KintonePageOutput.java
> +            GetRecordsByCursorResponseBody resp = client.record().getRecordsByCursor(cursorId);
`cursorId` が変わらないので無限ループしうる気がするんですが、ﾀﾞｲｼﾞｮｳﾌﾞなんでしょうか？

2022-03-16 11:00 UTC, d-hrs commented on src/main/java/org/embulk/output/kintone/KintonePageOutput.java
> +            GetRecordsByCursorResponseBody resp = client.record().getRecordsByCursor(cursorId);
https://developer.cybozu.io/hc/ja/articles/360040285292-kintone-Java-Client-%E3%81%AE%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB%E3%82%B3%E3%83%BC%E3%83%89%E9%9B%86#sample_record_cursor
公式の方法なのか

2022-03-16 11:03 UTC, d-hrs commented on src/main/java/org/embulk/output/kintone/KintonePageOutput.java
> +            GetRecordsByCursorResponseBody resp = client.record().getRecordsByCursor(cursorId);
なるほど、自分でカーソルを管理するわけじゃないのか
https://developer.cybozu.io/hc/ja/articles/360028843531-%E3%82%AB%E3%83%BC%E3%82%BD%E3%83%AB-API-%E3%82%92%E4%BD%BF%E3%81%A3%E3%81%A6%E3%83%AC%E3%82%B3%E3%83%BC%E3%83%89%E3%82%92%E4%B8%80%E6%8B%AC%E5%8F%96%E5%BE%97%E3%81%99%E3%82%8B

2022-03-16 11:04 UTC, d-hrs approved these changes

2022-03-17 01:06 UTC, merged